package crashlytics

object Constants {

  val DEPENDENCY_FABRIC_MAVEN = "https://maven.fabric.io/public"
  val DEPENDENCY_CRASHLYTICS_VERSION = "2.6.2"

  val PROPERTIES_API_KEY_KEY = "fabric.apiKey"
  val PROPERTIES_API_SECRET_KEY = "fabric.apiSecret"

  // Default values if version name/code isn't specified
  val DEFAULT_VERSION_NAME = "0.0" // Like in AndroidBuildHandler
  val DEFAULT_VERSION_CODE = 0
  // The header of autogenerated assets/crashlytics-build.properties
  val ASSET_CRASHLYTICS_BUILD_DESC = "Auto-generated properties file for crashlytics"

  // Default content of temporary file which created for writing release notes
  val NOTES_DESCRIPTION_MESSAGE_FORMAT = "Write and save here any notes about current release (%s)"

  // Ultra-secure token that must be sent with each api request
  val API_HEADER_DEVELOPER_TOKEN = "ed8fc3dc68a7475cc970eb1e9c0cb6603b0a3ea2"
  // API stuff
  val API_BASE_ENDPOINT = "https://api.crashlytics.com"
  val API_BASE_NOTES_FORMAT = s"$API_BASE_ENDPOINT/spi/v1/platforms/android/apps/%s/releases/%s/build_server/notes"
  val API_MAPPING_ENDPOINT = "https://cm.crashlytics.com"
  val API_MAPPING_UPLOAD_URL = s"$API_MAPPING_ENDPOINT/api/v3/platforms/android/code_mappings"
  val API_DISTRIBUTION_ENDPOINT = "https://distribution-uploads.crashlytics.com"
  val API_DISTRIBUTION_UPLOAD_FORMAT = s"$API_DISTRIBUTION_ENDPOINT/spi/v1/platforms/android/apps/%s/distributions"

}